#!/usr/bin/env bash

if [[ -z "$1" ]] ; then
  echo "FATAL: args required.  You likely want to run"
  echo "       $0 apt clean init"
  exit 1
fi

set -exo pipefail

for args in "$@" ; do
  case "${args}" in
    apt)
      apt-get update
      apt-get install -y \
        vim \
        curl \
        golang \
        git \
        tmate \
        tmux \
        mosh \
        tree
      ;;
    clean)
      rm -f \
        ~/.vimrc \
        ~/.gitconfig \
        ~/.bash_profile
      ;;
    init)
      curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      ln -s $HOME/work/dot-files/vim/vimrc ~/.vimrc
      ln -s $HOME/work/dot-files/gitconfig ~/.gitconfig
      ln -s $HOME/work/dot-files/bash_profile ~/.bash_profile
      vim -E -c PlugInstall -c q -c q
      vim -E -c GoInstallBinaries -c q -c q
      ;;
    linux)
      exec bash $0 apt clean init
      ;;
    *)
      echo "FATAL:  unknown options"
      exit 1
      ;;
  esac
done

echo "complete"
