" Use Vim settings, rather then Vi settings.
" This must be first, because it changes other options as a side effect.
set nocompatible
set nomodeline

" Ensure vim display correctly UTF-8 character
:set encoding=utf-8
:set fileencoding=utf-8

" Load vim-plug
source $HOME/work/dot-files/vim/plug.vim

" ================ General Config ====================

set number                      " Display line number
set ruler                       " Display line number in vim statusbar
set relativenumber              " ... relative to cursor location
set backspace=indent,eol,start  " Makes backspace key more powerful
set history=1000                " Store more :cmdline history
set showcmd                     " Show incomplete cmds down the bottom
set showmode                    " Show current mode down the bottom
set visualbell                  " No sounds
filetype off                    " Reset filetype detection first ...
filetype plugin indent on       " ... and enable filetype detection
set autowrite                   " Automatically save before :next, :make etc.


" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

" Set SpecialKey group visible characters to display in color
" SpecialKey group apply to trail, tab and nbsp
" highlight SpecialKey ctermfg=black ctermbg=white

" Display visual cue past colum 80
"set colorcolumn=80
highlight ColorColumn ctermfg=white ctermbg=lightgreen
highlight OverLength ctermbg=red ctermfg=white
match OverLength /\%>80v.\+/

"set nowrap       "Don't wrap lines
"set linebreak    "Wrap lines at convenient points

" ================ Folds ============================

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

" ============== Remember Cursor location ===========

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
if !has('nvim')
  set viminfo='10,\"100,:20,%,n~/.viminfo
endif

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END

" ================ Scrolling ========================

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescroll=1        " Activate sidescroll
set sidescrolloff=15    "Start scorlling when we're 15 char from end of line"

" From Jerome
set sw=2
set laststatus=2
syntax on
set showmatch
"set listchars=tab:▸\ ,trail:.
"set smarttab
"set list " show all hidden character

" From thomas
set smartcase     " ignore case if search pattern is all lowercase
                  " case-sensitive otherwise
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

"NERDTree settings
let NERDTreeShowFiles=1
let NERDTreeShowHidden=1
let NERDTreeMouseMode=2

" vim-go settings
let g:go_fmt_command = "goimports"
let g:go_list_type = "quickfix"     " Only use quickfix list to rise issue
let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_deadline = "5s"

"let g:rehash256 = 1
"let g:molokai_original = 1
"colorscheme molokai
"colorscheme solarized
"let g:solarized_termcolors=256
"set background=light
"set background=dark

source $HOME/work/dot-files/vim/keymaps.vim
source $HOME/work/dot-files/vim/abbreviations.vim

set nocursorcolumn              " Do not highlight column (speeds up highlighting)
set nocursorline                " Do not highlight cursor (speeds up highlighting)
set lazyredraw                  " Wait to redraw
set ttyfast                     " Indicate fast terminal conn for faster redraw
